configfile: "config.yaml"

base = config["base"]
samples = config["samples"]
replicates = config["replicates"]
translator = config["translator"]


rule all:
    input:
        f"{base}/sketches_done.txt"


rule translate_and_generate_csv:
    output:
        dataset = f"{base}/dataset.csv"
    params:
        samples=samples,
        replicates=replicates,
        base=base,
        translator=translator
    shell:
        """
        python3 scripts/translate_and_generate_csv.py \
            --samples {params.samples} \
            --replicates {params.replicates} \
            --base {params.base} \
            --translator {params.translator} \
            --dataset {output.dataset}
        """

rule sketch:
    input:
        dataset = f"{base}/dataset.csv"  # <-- use the path produced by translate_and_generate_csv
    output:
        touch(f"{base}/sketches_done.txt")  # global done file
    shell:
        "python scripts/sketch.py --dataset {input.dataset} --outdir {base}"
