configfile: "config.yaml"

base = config["base"]
results_folder = config["results_folder"]
samples = config["samples"]
ksize = config["ksize"]
translator = config["translator"]


rule all:
    input:
        f"{base}/{results_folder}/signature_generation_times.csv",
        f"{base}/{results_folder}/containment_times.csv",
        f"{base}/{results_folder}/fmh_omega_times.csv",
        f"{base}/{results_folder}/all_timings_merged.csv"


rule translate_and_generate_csv:
    output:
        dataset = f"{base}/{results_folder}/dataset.csv"
    params:
        samples=samples,
        base=base,
        translator=translator
    shell:
        """
        python3 scripts/translate_and_generate_csv.py \
            --samples {params.samples} \
            --base {params.base} \
            --translator {params.translator} \
            --dataset {output.dataset}
        """

rule sketch:
    input:
        dataset = f"{base}/{results_folder}/dataset.csv"  # <-- use the path produced by translate_and_generate_csv
    output:
        sig_times = f"{base}/{results_folder}/signature_generation_times.csv"
        #touch(f"{base}/{results_folder}/sketches_done.txt")  # global done file
    params:
        k = {ksize}
    shell:
        "python scripts/sketch.py --dataset {input.dataset} --ksize {params.k} --outdir {base}/{results_folder}"

rule compare_containments:
    input:
        sig_dir = os.path.join(base, results_folder),  # all sample_X folders live here
        sig_times = os.path.join(base, results_folder, "signature_generation_times.csv")  # <-- dependency
    output:
        containment_times = os.path.join(base, results_folder, "containment_times.csv")
    params:
        k = {ksize}
    shell:
        """
        python scripts/compare.py \
            --base {input.sig_dir} \
            --ksize {params.k} \
            --outcsv {output.containment_times}
        """


rule fmh_omega_summary:
    input:
        data = f"{base}/{results_folder}/dataset.csv",
        sig_times = f"{base}/{results_folder}/signature_generation_times.csv",
        containment_times = os.path.join(base, results_folder, "containment_times.csv")
    output:
        out_fmh_summary = f"{base}/{results_folder}/fmh_omega_times.csv"
    params:
        samples = samples,
        base = base,
        k = ksize,
        results = results_folder
    threads: 4
    shell:
        """
        python3 scripts/fmh.py \
        --base {params.base} \
        --dataset_csv {input.data} --ksize {params.k} \
        --results_dir {params.results} \
        --out_log {output.out_fmh_summary}
        """


rule merge_timings:
    input:
        sig = f"{base}/{results_folder}/signature_generation_times.csv",
        cont = f"{base}/{results_folder}/containment_times.csv",
        fmh = f"{base}/{results_folder}/fmh_omega_times.csv"
    output:
        merged = f"{base}/{results_folder}/all_timings_merged.csv"
    params:
        base_dir = f"{base}/{results_folder}"
    shell:
        """
        python3 scripts/merge_timings.py --base {params.base_dir}
        """
