configfile: "config.yaml"

base = config["base"]
samples = config["samples"]
replicates = config["replicates"]
translator = config["translator"]


rule all:
    input:
        f"{base}/snakemake_fmh_comparison_samples_10-1000/signature_generation_times.csv",
        f"{base}/snakemake_fmh_comparison_samples_10-1000/containment_times.csv",
        f"{base}/snakemake_fmh_comparison_samples_10-1000/fmh_omega_times.csv",
        f"{base}/snakemake_fmh_comparison_samples_10-1000/all_timings_merged.csv"


rule translate_and_generate_csv:
    output:
        dataset = f"{base}/snakemake_fmh_comparison_samples_10-1000/dataset.csv"
    params:
        samples=samples,
        base=base,
        translator=translator
    shell:
        """
        python3 scripts/translate_and_generate_csv.py \
            --samples {params.samples} \
            --base {params.base} \
            --translator {params.translator} \
            --dataset {output.dataset}
        """

rule sketch:
    input:
        dataset = f"{base}/snakemake_fmh_comparison_samples_10-1000/dataset.csv"  # <-- use the path produced by translate_and_generate_csv
    output:
        touch(f"{base}/snakemake_fmh_comparison_samples_10-1000/sketches_done.txt")  # global done file
    shell:
        "python scripts/sketch.py --dataset {input.dataset} --outdir {base}/snakemake_fmh_comparison_samples_10-1000"

rule compare_containments:
    input:
        sig_dir = os.path.join(base, "snakemake_fmh_comparison_samples_10-1000")  # all sample_X folders live here
    output:
        containment_times = os.path.join(base, "snakemake_fmh_comparison_samples_10-1000", "containment_times.csv")
    params:
        ksize = 7
    shell:
        """
        python scripts/compare.py \
            --base {input.sig_dir} \
            --ksize {params.ksize} \
            --outcsv {output.containment_times}
        """


rule fmh_omega_summary:
    input:
        f"{base}/dataset.csv"
    output:
        f"{base}/fmh_omega_times.csv"
    params:
        samples = samples,
        base = base
    threads: 4
    shell:
        """
        python3 scripts/fmh.py
        """


rule merge_timings:
    input:
        sig = f"{base}/signature_generation_times.csv",
        cont = f"{base}/containment_times.csv",
        fmh = f"{base}/fmh_omega_times.csv",
    output:
        merged = f"{base}/all_timings_merged.csv"
    params:
        base_dir = base
    shell:
        """
        python3 scripts/merge_timings.py --base {params.base_dir}
        """
